<?php

require_once "../_includes/bootstrap.inc.php";

final class Page extends BaseDBPage{

    const STATE_FROM_REQUESTED = 1;
    const STATE_DATA_SENT = 2;
    const STATE_REPORT_RESULT = 3;

    private RoomModel $room;
    private $state;

    public function __construct()
    {
        parent::__construct();
        $this->title = "Room listing";
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    protected function body(): string {
        $room = new RoomModel();
        $room->name = "Zmrzlina";
        return $this->m->render("roomForm", ["room"=>$room]);
    }

    private function getState() : int {

    }

    private function readPost() : void {

    }

    private function isDataValid() : bool {

    }

    private function insertData() : bool {
        $sql = "INSERT INTO room (name, no, phone) VALUES (:name, :no, :phone)";

        $stmt = $this->pdo->query($sql);
        $stmt->bindParam(':name', $this->room->name);
        $stmt->bindParam(':no', $this->room->no);
        $stmt->bindParam(':phone', $this->room->phone);

        return $stmt->execute();
    }

    private function redirect() : void {

    }
}

(new Page())->render();
